const layout = {
    name : "spanish",
    keys : [{81: {char: 'q', shift: 'Q'}},
            {87: {char: 'w', shift: 'W'}},
            {69: {char: 'e', shift: 'E', dead:'é', dead_shift: 'É'}},
            {82: {char: 'r', shift: 'R'}},
            {84: {char: 't', shift: 'T'}},
            {89: {char: 'y', shift: 'Y'}},
            {85: {char: 'u', shift: 'U', dead: 'ú', dead_shift: 'Ú'}},
            {73: {char: 'i', shift: 'I', dead: 'í', dead_shift: 'Í'}},
            {79: {char: 'o', shift: 'O', dead: 'ó', dead_shift: 'Ó'}},
            {80: {char: 'p', shift: 'P'}},
            {65: {char: 'a', shift: 'A', dead: 'á', dead_shift: 'Á', nextrow: true}},
            {83: {char: 's', shift: 'S'}},
            {68: {char: 'd', shift: 'D'}},
            {70: {char: 'f', shift: 'F'}},
            {71: {char: 'g', shift: 'G'}},
            {72: {char: 'h', shift: 'H'}},
            {74: {char: 'j', shift: 'J'}},
            {75: {char: 'k', shift: 'K'}},
            {76: {char: 'l', shift: 'L'}},
            {192:{char: 'ñ', shift: 'Ñ'}},
            {222:{name: 'dead', dead: '´'}},
            {16: {name: 'shift'}},
            ],
    states : [{state: 'dead', keys : ['press', 222, 'release', 222]},
              {state: 'shift', keys : ['press', 16]},
              {state: 'dead_shift', previous: 'dead', keys : ['press', 16]}]
              
}